/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    DisplayError: typeof import('./../components/state/DisplayError.vue')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    ILucideDelete: typeof import('~icons/lucide/delete')['default']
    IPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    IPhArrowRight: typeof import('~icons/ph/arrow-right')['default']
    IPhCheckCircle: typeof import('~icons/ph/check-circle')['default']
    IPhClockCountdown: typeof import('~icons/ph/clock-countdown')['default']
    IPhDotsThreeVertical: typeof import('~icons/ph/dots-three-vertical')['default']
    IPhGear: typeof import('~icons/ph/gear')['default']
    IPhInfo: typeof import('~icons/ph/info')['default']
    IPhMinus: typeof import('~icons/ph/minus')['default']
    IPhMoon: typeof import('~icons/ph/moon')['default']
    IPhPencil: typeof import('~icons/ph/pencil')['default']
    IPhPlus: typeof import('~icons/ph/plus')['default']
    IPhPlusCircle: typeof import('~icons/ph/plus-circle')['default']
    IPhQuestion: typeof import('~icons/ph/question')['default']
    IPhSun: typeof import('~icons/ph/sun')['default']
    IPhXCircle: typeof import('~icons/ph/x-circle')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
    LogYouIn: typeof import('./../components/LogYouIn.vue')['default']
    PageWrap: typeof import('./../components/PageWrap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindEmptyState: typeof import('./../components/state/tailwind-empty-state.vue')['default']
    TestComponent: typeof import('./../components/TestComponent.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
  }
}
